<?php

namespace Tests\Unit;

use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Tests\TestCase;
use Illuminate\Database\Eloquent\Factories\Factory;
use Illuminate\Support\Str;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithoutMiddleware;
use Illuminate\Support\Facades\DB;
use Exception;

class UserTest extends TestCase
{
    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->user = new User();

    }

    /**
     * A basic unit test example.
     *
     * @return void
     */
    public function test_example()
    {

        $r = new Request(['email' => 'CJY2jO7aoG@gmail.com', 'password' =>'4']);
        $this->assertTrue(!!$r->validate([
            'email' => 'required'
        ]));
       $this->assertFalse(Auth::attempt(['email' => 'CJY2jO7aoG@gmail.com', 'password' =>'4']));

        $this->assertTrue(true);
    }
}
